name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install system packages
      run: sudo apt-get install -y libusb-1.0-0-dev
    - name: Build
      run: make WITHOUT_READLINE=1
    - name: Upload exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: mspdebug
        path: mspdebug

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make WITHOUT_READLINE=1
    - name: Upload exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: mspdebug.exe
        path: mspdebug.exe

  macos:
    runs-on: macos-latest-large
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make WITHOUT_READLINE=1
    - name: Upload exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: mspdebug
        path: mspdebug
